name: wildfire
description: An conduit application with a database connection and data model.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.2 <4.0.0"

dependencies:
  conduit: ^4.3.6
  conduit_core: ^4.3.6
  conduit_postgresql: ^4.3.6

dev_dependencies:
  test: ^1.21.6
  conduit_test: ^4.3.6
