name: conduit_common_test
version: 3.1.0
homepage: https://github.com/conduit-dart/common-test
description: A collection of classes and function used for testing conduit and by the conduit test harness.
publish_to: none
environment:
  sdk: ">=2.19.0 <4.0.0"
dependencies:
  collection: ^1.17.1
  conduit_common: ^4.3.6
  conduit_core: ^4.3.7
  conduit_postgresql: ^4.3.6
dev_dependencies:
  lints: ^2.0.1
