name: application
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  dependency:
    path: ../dependency/
  meta: ^1.3.0

dev_dependencies:
  lint: ^1.5.0
  test: ^1.21.6

dependency_overrides:
  conduit_isolate_exec:
    path: ../../isolate_exec  
