name: conduit_common
version: 4.2.2
description: Common classes shared by conduit projects.
repository: https://github.com/bsutton/conduit-orm
environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  conduit_open_api: ^4.2.2
dev_dependencies:
  lints: ^2.0.1
