name: conduit_common
version: 4.1.4
description: Common classes shared by conduit projects.
repository: https://github.com/bsutton/conduit-orm
environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  conduit_open_api: ^4.1.4
dev_dependencies:
  lint: ^2.0.0
