name: conduit
version: 3.2.6
homepage: https://github.com/conduit-dart/conduit
description: A modern HTTP server application framework, ORM and OAuth2 provider with OpenAPI 3.0 integration. Foundation for REST, RPC or GraphQL services.
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  args: ^2.1.1
  analyzer: ^5.1.0
  collection: ^1.15.0
  conduit_common: ^3.2.5
  conduit_config: ^3.2.5
  conduit_isolate_exec: ^3.2.5
  conduit_open_api: ^3.2.5
  conduit_password_hash: ^3.2.5
  conduit_runtime: ^3.2.5
  crypto: ^3.0.2
  io: ^1.0.3
  logging: ^1.0.0
  meta: ^1.1.5
  path: ^1.6.1
  postgres: ^2.3.1
  pub_cache: ^0.3.0
  pub_semver: ^2.0.0
  yaml: ^3.1.0
dev_dependencies:
  http: ^0.13.0
  matcher: ^0.12.12
  mockito: ^5.3.2
  lints: ^2.0.1
  test: ^1.21.6
  fs_test_agent:
    path: ../fs_test_agent
  conduit_common_test:
    path: ../common_test
  conduit_test:
    path: ../test_harness
  web_socket_channel: ^2.2.0
executables:
  conduit: conduit
