name: fs_test_agent
version: 4.1.3
homepage: https://stablekernel.com
description: Utilities for writing tests to validate file system and Dart project directory operations.
environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  path: ^1.0.0
  pubspec: ^2.0.1
dev_dependencies:
  lint: ^2.0.0
  test: ^1.21.6
