name: fs_test_agent
version: 4.3.3
homepage: https://stablekernel.com
description: Utilities for writing tests to validate file system and Dart project directory operations.
environment:
  sdk: '>=2.19.0 <4.0.0'
dependencies:
  path: ^1.0.0
  pubspec: ^2.0.1
dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.6
