name: conduit_test
version: 4.1.0
homepage: https://github.com/conduit-dart/conduit
description: Utilities for writing automated tests for Conduit applications
environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  test: ^1.21.6
  matcher: ^0.12.12
  conduit_core: ^4.1.0
dev_dependencies:
  conduit_common_test:
    path: ../common_test
  test_core: ^0.4.18
