name: conduit_ci
version: 3.0.6
description: A simple command-line application.
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  conduit_common: ^3.0.6
  conduit_dev_tools: ^3.0.6
  dcli: ^1.5.1
  settings_yaml: ^3.0.3
  conduit_common_test: ^3.0.6
dev_dependencies: 
  lint: ^1.0.0
  pub_release: ^7.0.0
  test: ^1.16.5
dependency_overrides: 
  conduit_common: 
    path: ../common
  conduit_common_test:
    path: ../common_test
  conduit: 
    path: ../conduit
  conduit_open_api: 
    path: ../open_api
  conduit_codable: 
    path: ../codable
  conduit_config: 
    path: ../config
  conduit_dev_tools: 
    path: ../dev_tools
  conduit_isolate_exec: 
    path: ../isolate_exec
  conduit_password_hash: 
    path: ../password_hash
  conduit_runtime: 
    path: ../runtime
