name: conduit_password_hash
version: 4.1.8
homepage: https://github.com/conduit/dart-password-hash
description: PBKDF2 password hashing utility
environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  crypto: ^3.0.2
dev_dependencies:
  lint: ^2.0.0
  test: ^1.21.6
