name: conduit_password_hash
version: 4.3.3
homepage: https://github.com/conduit/dart-password-hash
description: PBKDF2 password hashing utility
environment:
  sdk: '>=2.19.0 <4.0.0'
dependencies:
  crypto: ^3.0.2
dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.6
