name: conduit_config
version: 4.1.0
description: A safe and convenient way to read YAML configuration files.
repository: https://github.com/conduit-dart/conduit-config.git
environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  conduit_runtime: ^4.1.0
  meta: ^1.3.0
  yaml: ^3.1.0
dev_dependencies:
  lint: ^2.0.0
  test: ^1.21.6
