name: conduit_open_api
version: 4.1.5
homepage: https://github.com/conduit-dart/open-api-dart
description: Data structures for OpenAPI (Swagger) specification. Reads and writes JSON specifications.
environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  conduit_codable: ^4.1.5
  meta: ^1.1.5
dev_dependencies:
  lint: ^2.0.0
  test: ^1.3.0
