name: Release

on:
  push:
    branches:
      - master
    
jobs:
  publish:
    if: |
      startsWith(github.event.head_commit.message, 'feat')
      || startsWith(github.event.head_commit.message, 'fix')
      || startsWith(github.event.head_commit.message, 'bug')
      || startsWith(github.event.head_commit.message, 'perf')
      || startsWith(github.event.head_commit.message, 'refactor')
      || startsWith(github.event.head_commit.message, 'revert')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dart-lang/setup-dart@v1
      with:
        sdk: stable
    - name: Prepare pub credentials
      run: |
        mkdir "$XDG_CONFIG_HOME/dart"
        echo '${{ secrets.PUB_CREDENTIALS }}' > "$XDG_CONFIG_HOME/dart/pub-credentials.json"
    - name: Git config
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
    - name: Install melos
      run: dart pub global activate melos
    - name: Format
      run: dart fix --apply && dart format --fix .
    - name: Uptick versions
      run: melos version --yes
    - name: Changelog
      run: git diff --unified=0 $GITHUB_SHA packages/cli/CHANGELOG.md | tail +6 | sed -e 's/^\+//' > CHANGES.txt
    - name: Cache Source
      run: melos cache-source
    - name: Publish package
      run: melos publish --no-dry-run --git-tag-version --yes
    - name: Push tags
      uses: CasperWA/push-protected@v2
      with:
        token: ${{ secrets.CONDUIT_PAT }}
        tags: true
        branch: master
    - name: Compute the release tag
      run: |
        echo "release_tag=v`cat packages/cli/pubspec.yaml | sed -nre 's/^version: [^0-9]*(([0-9]+\.)*[0-9]+).*/\1/p'`" >> $GITHUB_ENV
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.release_tag }}
        body_path: CHANGES.txt
    - name: Generate docs
      run: melos gen-docs && echo "mkdocs-monorepo-plugin=1.0.4" > requirements.txt
    - name: Deploy docs
      uses: mhausenblas/mkdocs-deploy-gh-pages@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CONFIG_FILE: mkdocs.yml
        EXTRA_PACKAGES: build-base
        REQUIREMENTS: requirements.txt
